"""This type stub file was generated by pyright."""

from collections.abc import Callable
from datetime import datetime
from typing import Any, Self
from xml.etree.ElementTree import Element

import requests
from _typeshed import Incomplete
from plexapi.base import PlexObject
from plexapi.client import PlexClient
from plexapi.library import LibrarySection
from plexapi.server import PlexServer
from plexapi.sync import SyncItem, SyncList
from plexapi.video import (
    ClipHistory,
    Episode,
    EpisodeHistory,
    Movie,
    MovieHistory,
    Season,
    Show,
)

class MyPlexAccount(PlexObject):
    FRIENDINVITE: str
    HOMEUSERS: str
    HOMEUSERCREATE: str
    EXISTINGUSER: str
    FRIENDSERVERS: str
    PLEXSERVERS: str
    FRIENDUPDATE: str
    HOMEUSER: str
    MANAGEDHOMEUSER: str
    SIGNIN: str
    SIGNOUT: str
    WEBHOOKS: str
    OPTOUTS: str
    LINK: str
    VIEWSTATESYNC: str
    PING: str
    VOD: str
    MUSIC: str
    DISCOVER: str
    METADATA: str
    _token: str
    _webhooks: list
    adsConsent: str | None
    adsConsentReminderAt: str | None
    adsConsentSetAt: str | None
    anonymous: str | None
    authToken: str
    backupCodesCreated: bool
    confirmed: bool
    country: str | None
    email: str | None
    emailOnlyAuth: bool
    experimentalFeatures: bool
    friendlyName: str | None
    guest: bool
    hasPassword: bool
    home: bool
    homeAdmin: bool
    homeSize: int
    id: int
    joinedAt: datetime
    locale: str | None
    mailingListActive: bool
    mailingListStatus: str | None
    maxHomeSize: int
    pin: str | None
    protected: bool
    rememberExpiresAt: datetime | None
    restricted: bool
    scrobbleTypes: list[int]
    thumb: str | None
    title: str | None
    twoFactorEnabled: bool
    username: str
    uuid: str | None
    subscriptionActive: bool
    subscriptionDescription: str | None
    subscriptionPaymentService: str | None
    subscriptionPlan: str | None
    subscriptionStatus: str | None
    subscriptionSubscribedAt: datetime | None
    profileAutoSelectAudio: bool
    profileDefaultAudioLanguage: str | None
    profileDefaultSubtitleLanguage: str | None
    profileAutoSelectSubtitle: int
    profileDefaultSubtitleAccessibility: int
    profileDefaultSubtitleForces: int
    services: Any | None
    def __init__(
        self,
        username: str | None = ...,
        password: str | None = ...,
        token: str | None = ...,
        session: requests.Session | None = ...,
        timeout: int | None = ...,
        code: str | None = ...,
        remember: bool = ...,
    ) -> None: ...
    def signout(self): ...
    @property
    def authenticationToken(self): ...
    def query(
        self,
        url: str,
        method: Callable | None = ...,
        headers: dict | None = ...,
        timeout: int | None = ...,
        **kwargs,
    ) -> str | dict | Element | None: ...
    def ping(self) -> bool: ...
    def device(self, name: str | None = ..., clientId: str | None = ...): ...
    def devices(self) -> list[MyPlexDevice]: ...
    def resource(self, name: str) -> MyPlexResource: ...
    def resources(self) -> list[MyPlexResource]: ...
    def sonos_speakers(self): ...
    def sonos_speaker(self, name): ...
    def sonos_speaker_by_id(self, identifier): ...
    def inviteFriend(
        self,
        user: MyPlexUser | str,
        server: PlexServer,
        sections: list[LibrarySection] | None = ...,
        allowSync: bool = ...,
        allowCameraUpload: bool = ...,
        allowChannels: bool = ...,
        filterMovies: dict | None = ...,
        filterTelevision: dict | None = ...,
        filterMusic: dict | None = ...,
    ): ...
    def createHomeUser(
        self,
        user: MyPlexUser | str,
        server: PlexServer,
        sections: list[LibrarySection] | None = ...,
        allowSync: bool = ...,
        allowCameraUpload: bool = ...,
        allowChannels: bool = ...,
        filterMovies: dict | None = ...,
        filterTelevision: dict | None = ...,
        filterMusic: dict | None = ...,
    ): ...
    def createExistingUser(
        self,
        user: MyPlexUser | str,
        server: PlexServer,
        sections: list[LibrarySection] | None = ...,
        allowSync: bool = ...,
        allowCameraUpload: bool = ...,
        allowChannels: bool = ...,
        filterMovies: dict | None = ...,
        filterTelevision: dict | None = ...,
        filterMusic: dict | None = ...,
    ): ...
    def removeFriend(self, user: MyPlexUser | str): ...
    def removeHomeUser(self, user: MyPlexUser | str) -> MyPlexAccount: ...
    def switchHomeUser(
        self, user: MyPlexUser | str, pin: str | None = ...
    ) -> MyPlexAccount: ...
    def setPin(self, newPin: str, currentPin: str | None = ...): ...
    def removePin(self, currentPin: str): ...
    def setManagedUserPin(self, user: MyPlexUser | str, newPin: str): ...
    def removeManagedUserPin(self, user: MyPlexUser | str): ...
    def acceptInvite(self, user: MyPlexUser | str): ...
    def cancelInvite(self, user: MyPlexUser | str): ...
    def updateFriend(
        self,
        user: MyPlexUser | str,
        server: PlexServer,
        sections: list[LibrarySection] | None = ...,
        removeSections: bool = ...,
        allowSync: bool | None = ...,
        allowCameraUpload: bool | None = ...,
        allowChannels: bool | None = ...,
        filterMovies: dict | None = ...,
        filterTelevision: dict | None = ...,
        filterMusic: dict | None = ...,
    ): ...
    def user(self, username: str) -> MyPlexUser: ...
    def users(self) -> list[MyPlexUser]: ...
    def pendingInvite(
        self, username: str, includeSent: bool = ..., includeReceived: bool = ...
    ) -> MyPlexInvite: ...
    def pendingInvites(
        self, includeSent: bool = ..., includeReceived: bool = ...
    ) -> list[MyPlexInvite]: ...
    def addWebhook(self, url: str): ...
    def deleteWebhook(self, url: str): ...
    def setWebhooks(self, urls: list[str]): ...
    def webhooks(self): ...
    def optOut(
        self, playback: Incomplete | None = ..., library: Incomplete | None = ...
    ): ...
    def syncItems(
        self, client: MyPlexDevice | None = ..., clientId: str | None = ...
    ) -> SyncList: ...
    def sync(
        self,
        sync_item: SyncItem,
        client: MyPlexDevice | None = ...,
        clientId: str | None = ...,
    ) -> SyncItem: ...
    def claimToken(self) -> str: ...
    def history(
        self, maxresults: int | None = ..., mindate: datetime | None = ...
    ) -> list[ClipHistory | EpisodeHistory | MovieHistory]: ...
    def onlineMediaSources(self): ...
    def videoOnDemand(self): ...
    def tidal(self): ...
    def watchlist(
        self,
        filter: str | None = ...,
        sort: str | None = ...,
        libtype: str | None = ...,
        maxresults: int | None = ...,
        **kwargs,
    ) -> list[Movie | Show]: ...
    def onWatchlist(self, item: Movie | Show) -> bool: ...
    def addToWatchlist(self, items: list[Movie | Show]) -> Self: ...
    def removeFromWatchlist(self, items: list[Movie | Show]) -> Self: ...
    def userState(self, item: Movie | Show): ...
    def isPlayed(self, item: Movie | Show | Season | Episode) -> bool: ...
    def markPlayed(self, item: Movie | Show | Season | Episode) -> Self: ...
    def markUnplayed(self, item: Movie | Show | Season | Episode) -> Self: ...
    def searchDiscover(
        self,
        query: str,
        limit: int = ...,
        libtype: str | None = ...,
        providers: str = ...,
    ) -> list[Movie | Show]: ...
    @property
    def viewStateSync(self) -> bool: ...
    def enableViewStateSync(self) -> None: ...
    def disableViewStateSync(self) -> None: ...
    def link(self, pin: str) -> None: ...
    def publicIP(self): ...
    def geoip(self, ip_address: str) -> GeoLocation: ...

class MyPlexUser(PlexObject):
    friend: bool
    allowCameraUpload: bool
    allowChannels: bool
    allowSync: bool
    email: str
    filterAll: str | None
    filterMovies: str | None
    filterMusic: str | None
    filterPhotos: str | None
    filterTelevision: str | None
    home: bool
    id: int
    protected: bool
    recommendationsPlaylistId: str | None
    restricted: str | None
    thumb: str | None
    title: str
    username: str
    servers: list[MyPlexServerShare]
    def get_token(self, machineIdentifier): ...
    def server(self, name): ...
    def history(
        self, maxresults: int | None = ..., mindate: datetime | None = ...
    ) -> list[ClipHistory | EpisodeHistory | MovieHistory]: ...

class MyPlexInvite(PlexObject):
    REQUESTS: str
    REQUESTED: str
    ...

class Section(PlexObject):
    def history(
        self, maxresults: int | None = ..., mindate: datetime | None = ...
    ) -> list[ClipHistory | EpisodeHistory | MovieHistory]: ...

class MyPlexServerShare(PlexObject):
    def section(self, name): ...
    def sections(self): ...
    def history(
        self, maxresults: int = ..., mindate: datetime | None = ...
    ) -> list[ClipHistory | EpisodeHistory | MovieHistory]: ...

class MyPlexResource(PlexObject):
    DEFAULT_LOCATION_ORDER: list[str]
    DEFAULT_SCHEME_ORDER: list[str]
    def preferred_connections(
        self,
        ssl: Incomplete | None = ...,
        locations: Incomplete | None = ...,
        schemes: Incomplete | None = ...,
    ): ...
    def connect(
        self,
        ssl: bool | None = ...,
        timeout: int | None = ...,
        locations: Incomplete | None = ...,
        schemes: Incomplete | None = ...,
    ) -> PlexServer | PlexClient.__class__: ...

class ResourceConnection(PlexObject): ...

class MyPlexDevice(PlexObject):
    def connect(
        self, timeout: int | None = ...
    ) -> PlexServer | PlexClient.__class__: ...
    def delete(self) -> None: ...
    def syncItems(self) -> SyncList: ...

class MyPlexPinLogin:
    PINS: str
    CHECKPINS: str
    POLLINTERVAL: int
    headers: dict
    finished: bool
    expired: bool
    token: str
    def __init__(
        self,
        session: requests.Session | None = ...,
        requestTimeout: int | None = ...,
        headers: dict | None = ...,
        oauth: bool = ...,
    ) -> None: ...
    @property
    def pin(self) -> str: ...
    def oauthUrl(self, forwardUrl: str | None = ...) -> str: ...
    def run(
        self, callback: Callable[[str], Any] | None = ..., timeout: int | None = ...
    ) -> None: ...
    def waitForLogin(self) -> bool: ...
    def stop(self) -> None: ...
    def checkLogin(self) -> bool: ...

class AccountOptOut(PlexObject):
    CHOICES: Incomplete
    def optIn(self) -> None: ...
    def optOut(self) -> None: ...
    def optOutManaged(self) -> None: ...

class UserState(PlexObject): ...
class GeoLocation(PlexObject): ...
